### ISSUE TITLE
DiffOrig is genius 

### ISSUE THREAD

**Issue by florianbeer** [jfrazelle/.vim#8]
Just came here to tell you that I love your [DiffOrig](https://github.com/jfrazelle/.vim/blob/master/vimrc#L140) command. It's really handy for me since I've switched to persistent undo in my .vimrc so I can't just `uuuuuu` to remember what I changed since I started editing.
Thank you!

I featured your snippet here: http://vimrcfu.com/snippet/214

PS: I also snatched *nerdy* from your Dockerfiles :grin:

**Comment by lieuwex** [comment]
@florianbeer http://vimdoc.sourceforge.net/htmldoc/diff.html#:DiffOrig

**Comment by jfrazelle** [comment]
Ya i cannot take credit for this genius :)
